### ISSUE TITLE
Tuesday October 24th

### ISSUE THREAD

**Issue by eeeva97** [ambertin/sds192-mp2#2]
We found the average size of donations by specific jobs (as well as the median and number of donations). Next, we will link the donations to specific candidates and figure out which party they donated to and how often they won.

**Comment by ambertin** [comment]
I've been looking into linking the donations to the committees and then to the candidates, and the problem is that most of the committees are either related to the senate or to a presidential election and I can't find a way to just pick out the committees that donate to house races. Then additionally, there is the problem of the fact that multiple occupations donate to the same committees, so it's really hard to do a join and then summarize which occupation was the most successful (I don't think that made any sense so I'll explain it again tomorrow). I think we should instead attempt to focus on partisanship of different jobs across income levels if possible.
